# spring datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pentoryall
    username: ohgiraffers
    password: ohgiraffers

  # file upload config
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: C:/00_Pactoryall/Pentoryall2

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

## image upload dir
#image:
#  image-dir: src/main/resources/upload/

# image upload dir
image:
  image-dir: C:/00_Pactoryall/
