# [spring]
server:
  port: 8080
  error:
    whitelabel.enabled: false
spring:
  config:
    activate:
      on-profile: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
  # spring.thymeleaf
  thymeleaf:
    cache: false
    check-template-location: true
  # spring.datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pentoryall
    username: ohgiraffers
    password: ohgiraffers
  # spring.email
  mail:
    host: smtp.gmail.com  # SMTP 서버 호스트
    port: 587             # SMTP 서버 포트
    username: EMAIL_ID
    password: EMAIL_PW
    properties:
      mail:
        smtp:
          auth: true      # 사용자 인증 시도 여부 - 기본값 false
          timeout: 5000   # Socket Read Timeout 시간(ms) - 기본값 : 무한대
          starttls:
            enable: true  # StartTLS 활성화 여부 - 기본값 false 이메일인증 끝
  # spring.servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}
# -------------------------------------------------
# [mybatis]
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
# -------------------------------------------------
# [image] image upload directory
image:
  image-dir: ${java.io.tmpdir}

# -------------------------------------------------
# [PortOne]
portone:
  api:
    key: API_KEY
    secret: API_SECRET
