# spring datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pentoryall
    username: ohgiraffers
    password: ohgiraffers
  mail: # 이메일인증 시작
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${mail.username} # 이메일 아이디, 주소가 test@gmail.com이면 test
    password: ${mail.password} # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 - 기본값 false
          timeout: 5000 # Socket Read Timeout 시간(ms) - 기본값 : 무한대
          starttls:
            enable: true # StartTLS 활성화 여부 - 기본값 false 이메일인증 끝

  # file upload config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/yunii/Desktop/Pentoryall

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

# image upload dir
image:
  image-dir: src/main/resources/upload/